CREATE DATABASE Bambi;

GO

USE Bambi

GO

CREATE TABLE Clients(
	ClientID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	FirstName NVARCHAR(20) NOT NULL,
	LastName NVARCHAR(20),
	PhoneNumber NVARCHAR(30),
	Instagram NVARCHAR(30),
	Note NVARCHAR(200),
	RegisterDate DATETIME NOT NULL DEFAULT GETDATE(),
	Active BIT NOT NULL DEFAULT 1
)

GO

CREATE TABLE States(
	StateID INT NOT NULL PRIMARY KEY,
	State NVARCHAR(200) NOT NULL
)

GO

CREATE TABLE Cities(
	CityID INT NOT NULL PRIMARY KEY,
	City NVARCHAR(200) NOT NULL,
	StateID INT NOT NULL FOREIGN KEY REFERENCES States(StateID)
)

GO

CREATE TABLE ClientAddress(
	ClientAddressID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	ClientID INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientID),
	Street NVARCHAR(30),
	Number NVARCHAR(10),
	Floor NVARCHAR(10),
	Apartment NVARCHAR(10),
	CityID INT NOT NULL FOREIGN KEY REFERENCES Cities(CityID)
)

GO

CREATE TABLE Status(
	StatusID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	Status NVARCHAR(20)
)

GO

CREATE TABLE Jobs(
	JobID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	ClientID INT NOT NULL FOREIGN KEY REFERENCES Clients(ClientID),
	JobDate DATE,
	StartTime TIME,
	EndTime TIME,
	StatusID INT NOT NULL DEFAULT 4
)

GO

CREATE TABLE Deposits(
	DepositID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	JobID INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobID),
	Total MONEY,
	Paid BIT 
)

GO

CREATE TABLE Prices(
	PriceID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	JobID INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobID),
	Total MONEY,
	Paid BIT 
)

GO

CREATE TABLE Services(
	ServiceID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	Service NVARCHAR(30),
	Price MONEY,
	Duration TIME,
	Active BIT NOT NULL DEFAULT 1
)

GO

CREATE TABLE ServicesJobs(
	ServiceJobID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	JobID INT NOT NULL FOREIGN KEY REFERENCES Jobs(JobID),
	ServiceID INT NOT NULL FOREIGN KEY REFERENCES Services(ServiceID),
)

GO

CREATE TABLE Groups(
	GroupID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	GroupName NVARCHAR(50),
	Active BIT NOT NULL DEFAULT 1
)

GO

CREATE TABLE ServicesGroups(
	ServiceGroupID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	ServiceID INT NOT NULL FOREIGN KEY REFERENCES Services(ServiceID),
	GroupID INT NOT NULL FOREIGN KEY REFERENCES Groups(GroupID)
)

GO

CREATE TABLE Submissions(
	SubmissionID INT NOT NULL PRIMARY KEY IDENTITY (1, 1),
	ClientID INT FOREIGN KEY REFERENCES Clients(ClientID),
	JobDate DATE,
	StartTime TIME,
	EndTime TIME,
	Price MONEY,
	StatusID INT NOT NULL FOREIGN KEY REFERENCES Status(StatusID) DEFAULT 1,
	SubmissionDate DATETIME NOT NULL DEFAULT GETDATE()
)

GO